plone/Products.Archetypes

- CHANGES.txt
- Products/Archetypes/Marshall.py
These changes allow additional fields to be round-tripped in the structure importer when dealing with AT content. They are useful for using the structure importer for creating initial state of applications, as it's likely there will be `mode='r'` fields that need an initial value populating.
> Improvements to Archetypes integration with structure export/import

- Products/Archetypes/skins/archetypes/createObject.cpy
- Products/Archetypes/skins/archetypes/createObject.cpy.metadata
This PR moves a slightly modified version (the existence of the portal_factory is checked) of the createObject from ATContentTypes to Archetypes.
It allows to add AT content in Plone 5 TTW without depending on ATContentTypes.
> moved createObject from ATContentTypes

- Products/Archetypes/skins/archetypes/widgets/js/picklist.js
I ran into a situation where the available options in a picklist had the same names but different values. Once the first one was selected, I couldn't select another entry with the same name because the `text` property was being compared instead of the `value` property.
> compare picklist entry value not text

- CHANGES.rst
- Products/Archetypes/tests/test_pawidgets.py
We were mocking plone.app.widgets.utils.getUtility,but this was nowhere used.
I see I cleaned up the usage of it myself a few months ago.
Current plone.app.widgets.utils has no getUtility anymore.
But: I have got no idea why I got the following failures on master locally while Jenkins is happy:
```
Error in test test_multi_valued (
Products.Archetypes.tests.test_pawidgets.RelatedItemsWidgetTests)
Traceback (most recent call last):
File "/Users/maurits/shared-eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340,
in run testMethod()
File ".../5.0/src/Products.Archetypes/Products/Archetypes/tests/test_pawidgets.py", 
line 323, in test_multi_valued
with mock.patch('plone.app.widgets.utils.getUtility') as mock_method:
File "/Users/maurits/shared-eggs/mock-1.0.1-py2.7.egg/mock.py", line …
```
> No longer try to mock plone.app.widgets in tests.

- CHANGES.rst
- Products/Archetypes/skins/archetypes/edit_macros.pt
...fixing form tabs on siteswith plone.app.widgets 1.x installed.
> Fix Plone 4 Archetypes edit forms to use autotoc pattern markup

- CHANGES.rst
- Products/Archetypes/Widget.py
- Products/Archetypes/tests/test_pawidgets.py
values; fixes inability to clear an already set date or datetime in Archetypes fields.
> DateWidget, DatetimeWidget (pick-a-date) now able to clear previous

- CHANGES.rst
- Products/Archetypes/ExtensibleMetadata.py
`Product.Archetypes.Field.validate` invokes `validate_content_types` if `allowable_content_types` is set on a field. In case of the description field, this can lead to surprising validation results because the method is trying to guess the content type using the `mimetypes_registry`. Example: If you enter the word 'Stammdaten' (german for master data) as the first word into a description field, you see a validation error telling you that the MIME type 'video/quicktime' is not allowed for the field. This is because the `mimetypes_registry` is trying to guess the MIME type of the string 'Stammdaten' using a test in `Products.MimetypesRegistry.mime_types.magic`. The term 'Stammdaten' matches the following test pattern:
[4, 'string', '=', 'mdat', 'video/quicktime']
(letters 'mdat' starting at …
> no allowable_content_types for description (avoid validation)

- CHANGES.rst
- Products/Archetypes/profiles/sample_types/types/ATBIFolder.xml
- Products/Archetypes/profiles/sample_types/types/ComplexType.xml
- Products/Archetypes/profiles/sample_types/types/DDocument.xml
- Products/Archetypes/profiles/sample_types/types/Fact.xml
- Products/Archetypes/profiles/sample_types/types/MySimpleType.xml
- Products/Archetypes/profiles/sample_types/types/Refnode.xml
- Products/Archetypes/profiles/sample_types/types/SimpleBTreeFolder.xml
- Products/Archetypes/profiles/sample_types/types/SimpleFile.xml
- Products/Archetypes/profiles/sample_types/types/SimpleFolder.xml
- Products/Archetypes/profiles/sample_types/types/SimpleProtectedType.xml
- Products/Archetypes/profiles/sample_types/types/SimpleType.xml
Use png instead.
We could change the document_icon and folder_icon in `ArchetypeTool.registerClasses` and `BaseFolder.content_icon` too, but the first one is already not called anywhere in Plone 4.3, and content_icons should be done in the GS profile.  Or in css actually.
> Don't use document/folder_icon.gif in the test profile.

- CHANGES.rst
- Products/Archetypes/athistoryaware.py
> Make AnnotationStorage awareness of OFS.HistoryAware optional

- CHANGES.rst
- Products/Archetypes/utils.py
Needed to work with latest zope.i18nmessageid 4.0.3 release (and later).
> Default display value of a Vocabulary i18n-message must be unicode.

- CHANGES.rst
- Products/Archetypes/skins/archetypes/widgets/js/textcount.js
This is for example used by PloneFormGen when you set a maximum character count for a text field.
This is the last javascript file in Archetypes that still used the old `jq` variable.
> Use $ instead of jq in textcount.js. [Plone 4.3]

- CHANGES.rst
- Products/Archetypes/skins/archetypes/widgets/field.pt
There is a problem with the current implementation in the `1.9.x` branch with the postback attribute.
**Steps to reproduce:**
1. Save an object with two populated fields.
2. Edit this object, make the first one empty and now edit the second in a way, an error message is triggered.
**Expected result:**
The first field should **stay** empty, since this new value has been explicitly been submitted. Also the error happened in a different field.
**Observed result:**
The first field is populated with the original value.
The problem lies in the following line:
```python
value = widget.postback and request.get(fieldName, value) or value
```
Just as reminder from the docs what postback actually does:
> Common Widget Attributes 
postback -  If this is enabled, then when an error is raised, the …
> Fix bug with Widget's postback attribute [Plone 4.3]

- CHANGES.rst
- Products/Archetypes/skins/archetypes/widgets/field.pt
This PR is identical to https://github.com/plone/Products.Archetypes/pull/80, but applies for the master branch.
It also fixes a problem, that was only present here: When widget.postback is set to False for a string field, then it is populated with "False" as string value. I looked up, why the implementation differed and it was said to ensure, that boolean fields are correctly populated with their default values. I checked that too in my local setup and it works like expected.
> Fix bug with Widget's postback attribute

- CHANGES.rst
- Products/Archetypes/ReferenceEngine.py
... from a object that is gone.
Fixes https://github.com/plone/plone.app.contenttypes/issues/41
> Prevent AttributeError on deleting a Reference 

- CHANGES.rst
- Products/Archetypes/skins/archetypes/widgets/js/textcount.js
- Fixed textcount.js support jquery>1.6.
- Fixed a bug (that it was possible to enter text length over maxlimit) by replacing maxlimit alert() with highlighting textcountfield.[vkarppinen]
> Fix bugs with old jquery version and textlimit alert

- Products/Archetypes/Field.py
Old method doc hinted that it was safe to call getAccessor return value, as is done in many places (`field.getAccessor(context)()`). Discussed in #94.
> Update Field::getAccessor() doc to reflect fallback behavior

- CHANGES.rst
- Products/Archetypes/ReferenceEngine.py
from object that is gone.
Backport from master #91. Fixes plone/plone.app.contenttypes#41.
> Prevent AttributeError on deleting a Reference

- Products/Archetypes/skins/archetypes/unicodeTestIn.py
- Products/Archetypes/tests/test_widgets.py
- news/125.bugfix
Fixes issue #125 for branch 1.9.x (Plone 4.3).
This contains performance tests, which are ignored by default, but can be activated by exporting a number:
```
$ export AT_UNICODETESTIN=3000
$ bin/test -s Products.Archetypes -m test_widgets -t test_unicodeTestIn
...
Testing unicodeTestIn with 3000 items, and 50 selected.
...
```
Timings before this fix:
```
First test part finished in 4.2931 seconds
Second test part finished in 12.6825 seconds
```
Timings after this fix:
```
First test part finished in 0.0373 seconds
Second test part finished in 0.2010 seconds
```
And with the fix and 30,000 items:
```
First test part finished in 0.0374 seconds
Second test part finished in 2.0301 seconds
```
> Fixed slowness in unicodeTestIn script used by keyword template.

- Products/Archetypes/tests/test_pawidgets.py
- news/124.bugfix
Problem: refactoring plone.app.widgets is not easy with too detailed expectations on the output of the pattern_options. Its also outside the scope of this test.
Solution: check if there are pattern_options, but now what they are exactly.
> Make QueryStringWidgetTests more robust/independent of implementation details

- Products/Archetypes/Widget.py
- news/2832.bugfix
Fixes https://github.com/plone/Products.CMFPlone/issues/2832
> Fixed UnicodeEncodeError when editing Archetypes rich text.

- Products/Archetypes/skins/archetypes/date_components_support.py
- news/133.bugfix
See https://github.com/plone/Products.Archetypes/issues/133
We missed a spot in commit cf5d40b414b6339fa3a2a49e2d18dad8767de11c.
Jenkins started [failing since the new year](https://jenkins.plone.org/job/plone-5.2-python-2.7/1204/testReport/junit/Products.Archetypes.tests.test_date_components_support_script/TestDateComponentsSupportDefault/testYears/):
```
{'selected': 1, 'id': 2020, 'value': 2020} != {'selected': None, 'id': 2020, 'value': 2020}
- {'id': 2020, 'selected': 1, 'value': 2020}
?                          ^
+ {'id': 2020, 'selected': None, 'value': 2020}
?                          ^^^^
File "/srv/python2.7/lib/python2.7/unittest/case.py", line 329, in run
testMethod()
File "/home/jenkins/.buildout/eggs/cp27m/Products.Archetypes-1.16.3-py2.7.egg/Products/Archetypes/tests/test_da …
```
> Lifted the ceiling for maximum date 2020 to 2050 in all places

- Products/Archetypes/event.py
- Products/Archetypes/interfaces/event.py
- Products/Archetypes/mimetype_utils.py
- Products/Archetypes/tests/events.txt
- news/462.bugfix
`zope.component.interfaces` has long been a backwards compatibility import for `zope.interface.interfaces`, but not anymore.
See the [660 failures](https://jenkins.plone.org/job/pull-request-5.2-2.7/2060/) on Jenkins 5.2-2.7 for PR https://github.com/plone/buildout.coredev/pull/725.
We need this change, to be able to use Zope 4.6.2 in Plone 5.2, unless we decide to keep the old zope.component 4.
This change works in both cases.
> Fixed incompatibility with zope.component 5.
